import "server-only";

export type ApiCatalogRoute = {
  module: string;
  method: string;
  path: string;
  documentedPath: string;
  purpose: string;
  caller: string;
  whenCalled: string;
  auth: string;
  pagination: string;
  responseSizeRisk: string;
  status: string;
  notes: string;
};

export const API_CATALOG_ROUTES = [
  {
    "module": "Auth",
    "method": "GET",
    "path": "/api/auth/session",
    "documentedPath": "/api/auth/session",
    "purpose": "อ่าน session ผู้ใช้ปัจจุบัน",
    "caller": "ทุกหน้า",
    "whenCalled": "on app load / refresh",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "มีแล้วใน repo"
  },
  {
    "module": "Auth",
    "method": "GET",
    "path": "/api/auth/login",
    "documentedPath": "/api/auth/login",
    "purpose": "เริ่ม RMC SSO login",
    "caller": "Login",
    "whenCalled": "เมื่อกดเข้าสู่ระบบ",
    "auth": "Public",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "มีแล้วใน repo"
  },
  {
    "module": "Auth",
    "method": "GET",
    "path": "/api/auth/callback/rmc-sso",
    "documentedPath": "/api/auth/callback/rmc-sso",
    "purpose": "รับ callback จาก RMC SSO",
    "caller": "SSO provider",
    "whenCalled": "หลัง login สำเร็จ",
    "auth": "Public/OIDC",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "มีแล้วใน repo"
  },
  {
    "module": "Auth",
    "method": "GET",
    "path": "/api/auth/logout",
    "documentedPath": "/api/auth/logout",
    "purpose": "ออกจากระบบและล้าง session",
    "caller": "Header/Profile",
    "whenCalled": "เมื่อกด logout",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "มีแล้วใน repo"
  },
  {
    "module": "Assistant",
    "method": "POST",
    "path": "/api/assistant/chat",
    "documentedPath": "/api/assistant/chat",
    "purpose": "คุยกับผู้ช่วย Safety",
    "caller": "Floating assistant",
    "whenCalled": "เมื่อผู้ใช้ส่งข้อความ",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "มีแล้วใน repo"
  },
  {
    "module": "Locations",
    "method": "GET",
    "path": "/api/locations/plants",
    "documentedPath": "/api/locations/plants",
    "purpose": "รายการโรงงานสำหรับ check-in/search",
    "caller": "Check-in, Admin",
    "whenCalled": "เมื่อเปิด filter โรงงาน",
    "auth": "User",
    "pagination": "Required page/pageSize",
    "responseSizeRisk": "High if unpaged",
    "status": "Existing",
    "notes": "แยกจาก all locations เพราะข้อมูลเยอะ"
  },
  {
    "module": "Locations",
    "method": "GET",
    "path": "/api/locations/offices",
    "documentedPath": "/api/locations/offices",
    "purpose": "รายการสำนักงานสำหรับ check-in/search",
    "caller": "Check-in, Admin",
    "whenCalled": "เมื่อเปิด filter สำนักงาน",
    "auth": "User",
    "pagination": "Required page/pageSize",
    "responseSizeRisk": "High if unpaged",
    "status": "Existing",
    "notes": "แยกประเภทเพื่อ index/cache ได้ดี"
  },
  {
    "module": "Locations",
    "method": "GET",
    "path": "/api/locations/sites",
    "documentedPath": "/api/locations/sites",
    "purpose": "รายการ site งานสำหรับ check-in/search",
    "caller": "Check-in, Admin",
    "whenCalled": "เมื่อเปิด filter site งาน",
    "auth": "User",
    "pagination": "Required page/pageSize",
    "responseSizeRisk": "High if unpaged",
    "status": "Existing",
    "notes": "site อาจเปลี่ยนบ่อยและมีปริมาณมาก"
  },
  {
    "module": "Locations",
    "method": "GET",
    "path": "/api/locations/custom",
    "documentedPath": "/api/locations/custom",
    "purpose": "รายการ location ที่ admin เพิ่มเอง",
    "caller": "Admin, Check-in",
    "whenCalled": "เมื่อเลือก custom",
    "auth": "User",
    "pagination": "Required page/pageSize",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "รองรับ location นอก master"
  },
  {
    "module": "Locations",
    "method": "GET",
    "path": "/api/locations/map",
    "documentedPath": "/api/locations/map?type=&bbox=&zoom=",
    "purpose": "marker สำหรับแผนที่ตาม viewport",
    "caller": "Check-in map",
    "whenCalled": "เมื่อ pan/zoom map",
    "auth": "User",
    "pagination": "Required bbox + cap",
    "responseSizeRisk": "Critical if returns all",
    "status": "Existing",
    "notes": "ต้องใช้ spatial index"
  },
  {
    "module": "Locations",
    "method": "GET",
    "path": "/api/locations/search",
    "documentedPath": "/api/locations/search?type=&q=&limit=",
    "purpose": "autocomplete location",
    "caller": "Check-in search box",
    "whenCalled": "เมื่อพิมพ์ค้นหา",
    "auth": "User",
    "pagination": "Required limit <= 50",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "ค้นด้วย code/name/external key"
  },
  {
    "module": "Locations",
    "method": "GET",
    "path": "/api/locations/:id",
    "documentedPath": "/api/locations/:id",
    "purpose": "รายละเอียด location เดียว",
    "caller": "Check-in detail, Admin",
    "whenCalled": "เมื่อเลือก marker/card",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "โหลด detail แยกจาก list"
  },
  {
    "module": "Locations",
    "method": "POST",
    "path": "/api/locations",
    "documentedPath": "/api/locations",
    "purpose": "เพิ่ม location ใหม่",
    "caller": "Admin",
    "whenCalled": "เมื่อ admin submit form",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "เขียนลง locations"
  },
  {
    "module": "Locations",
    "method": "PATCH",
    "path": "/api/locations/:id",
    "documentedPath": "/api/locations/:id",
    "purpose": "แก้ไข location",
    "caller": "Admin",
    "whenCalled": "เมื่อ admin save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "ต้อง audit"
  },
  {
    "module": "Locations",
    "method": "DELETE",
    "path": "/api/locations/:id",
    "documentedPath": "/api/locations/:id",
    "purpose": "soft delete location",
    "caller": "Admin",
    "whenCalled": "เมื่อ admin ลบ",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "soft delete เท่านั้น"
  },
  {
    "module": "Locations",
    "method": "GET",
    "path": "/api/safety-effort/locations",
    "documentedPath": "/api/safety-effort/locations",
    "purpose": "รายการ location เดิมใน repo",
    "caller": "Check-in/Admin",
    "whenCalled": "ปัจจุบันใช้ query type/search/limit",
    "auth": "User",
    "pagination": "Optional limit",
    "responseSizeRisk": "High if raised too much",
    "status": "Existing",
    "notes": "ควรค่อย migrate ไปเส้นแยกด้านบน"
  },
  {
    "module": "Locations",
    "method": "POST",
    "path": "/api/safety-effort/locations",
    "documentedPath": "/api/safety-effort/locations",
    "purpose": "เพิ่ม location เดิมใน repo",
    "caller": "Admin",
    "whenCalled": "Admin create",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "มีแล้ว"
  },
  {
    "module": "Locations",
    "method": "GET",
    "path": "/api/safety-effort/locations/:id",
    "documentedPath": "/api/safety-effort/locations/:id",
    "purpose": "อ่าน location เดิมรายตัว",
    "caller": "Admin/Check-in",
    "whenCalled": "Detail",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "มีแล้ว"
  },
  {
    "module": "Locations",
    "method": "PATCH",
    "path": "/api/safety-effort/locations/:id",
    "documentedPath": "/api/safety-effort/locations/:id",
    "purpose": "แก้ location เดิม",
    "caller": "Admin",
    "whenCalled": "Save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "มีแล้ว"
  },
  {
    "module": "Locations",
    "method": "DELETE",
    "path": "/api/safety-effort/locations/:id",
    "documentedPath": "/api/safety-effort/locations/:id",
    "purpose": "soft delete location เดิม",
    "caller": "Admin",
    "whenCalled": "Delete",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "มีแล้ว"
  },
  {
    "module": "Check-in",
    "method": "POST",
    "path": "/api/checkins",
    "documentedPath": "/api/checkins",
    "purpose": "บันทึก check-in พร้อม GPS จริงและ selected location",
    "caller": "Check-in",
    "whenCalled": "หลังผู้ใช้ยืนยันสถานที่",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "คืน checkinId เพื่อเริ่มกิจกรรม"
  },
  {
    "module": "Check-in",
    "method": "GET",
    "path": "/api/checkins/me",
    "documentedPath": "/api/checkins/me?from=&to=&page=&pageSize=",
    "purpose": "ประวัติ check-in ของฉัน",
    "caller": "Profile/History",
    "whenCalled": "เปิดประวัติ",
    "auth": "User",
    "pagination": "Required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "filter ตามวันที่"
  },
  {
    "module": "Check-in",
    "method": "GET",
    "path": "/api/checkins",
    "documentedPath": "/api/checkins?locationId=&userId=&from=&to=&page=&pageSize=",
    "purpose": "admin ดู check-in ทั้งหมด",
    "caller": "Safety Admin",
    "whenCalled": "เปิดรายงาน",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": "ต้องมี indexes ตาม user/date/location"
  },
  {
    "module": "Check-in",
    "method": "GET",
    "path": "/api/checkins/:id",
    "documentedPath": "/api/checkins/:id",
    "purpose": "รายละเอียด check-in",
    "caller": "Admin/History",
    "whenCalled": "เปิดรายการ",
    "auth": "User/Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "รวม attachments summary"
  },
  {
    "module": "Safety Effort",
    "method": "GET",
    "path": "/api/safety-effort",
    "documentedPath": "/api/safety-effort",
    "purpose": "API module briefing เดิม",
    "caller": "Dev/Admin",
    "whenCalled": "debug/discovery",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "มีแล้ว"
  },
  {
    "module": "Safety Effort",
    "method": "POST",
    "path": "/api/safety-effort/activities",
    "documentedPath": "/api/safety-effort/activities",
    "purpose": "เริ่มกิจกรรม Safety Effort จาก check-in",
    "caller": "Category/Activity",
    "whenCalled": "หลังเลือก activity",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "สร้าง safety_activities"
  },
  {
    "module": "Safety Effort",
    "method": "GET",
    "path": "/api/safety-effort/activities/me",
    "documentedPath": "/api/safety-effort/activities/me?status=&page=&pageSize=",
    "purpose": "กิจกรรมของฉัน",
    "caller": "Dashboard/Profile",
    "whenCalled": "เปิด dashboard",
    "auth": "User",
    "pagination": "Required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "ใช้ resume draft/submitted"
  },
  {
    "module": "Safety Effort",
    "method": "GET",
    "path": "/api/safety-effort/activities/:id",
    "documentedPath": "/api/safety-effort/activities/:id",
    "purpose": "รายละเอียดกิจกรรม",
    "caller": "Linewalk/Summary",
    "whenCalled": "เปิดกิจกรรม",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "เชื่อม checkin"
  },
  {
    "module": "Safety Effort",
    "method": "PATCH",
    "path": "/api/safety-effort/activities/:id",
    "documentedPath": "/api/safety-effort/activities/:id",
    "purpose": "อัปเดตสถานะกิจกรรม",
    "caller": "Linewalk/Summary",
    "whenCalled": "save draft/submit",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "status draft/submitted/cancelled"
  },
  {
    "module": "Safety Effort",
    "method": "POST",
    "path": "/api/safety-effort/submissions",
    "documentedPath": "/api/safety-effort/submissions",
    "purpose": "บันทึก Linewalk/Safety Contact พร้อมคำตอบและรูปแบบ structured",
    "caller": "Assessment Summary",
    "whenCalled": "เมื่อยืนยันบันทึก",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "canonical report source ไม่ใช้ localStorage"
  },
  {
    "module": "Safety Effort",
    "method": "GET",
    "path": "/api/safety-effort/submissions/me",
    "documentedPath": "/api/safety-effort/submissions/me?page=&pageSize=",
    "purpose": "ประวัติ submission ของผู้ใช้",
    "caller": "Profile/History",
    "whenCalled": "เปิดประวัติ",
    "auth": "User",
    "pagination": "Required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "อ่านจาก safety_effort_submissions"
  },
  {
    "module": "Safety Effort",
    "method": "GET",
    "path": "/api/safety-effort/submissions",
    "documentedPath": "/api/safety-effort/submissions?from=&to=&activityType=&page=&pageSize=",
    "purpose": "รายงาน submissions ทั้งระบบ",
    "caller": "Safety Admin Report/Export",
    "whenCalled": "เปิดรายงาน",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": "admin report source"
  },
  {
    "module": "Safety Effort",
    "method": "PATCH",
    "path": "/api/safety-effort/submissions/:id",
    "documentedPath": "/api/safety-effort/submissions/:id",
    "purpose": "แก้ข้อมูลรายงาน submission",
    "caller": "Safety Admin Export Report",
    "whenCalled": "แก้ข้อมูลรายงาน",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "อัปเดตเฉพาะ report fields"
  },
  {
    "module": "Safety Effort",
    "method": "DELETE",
    "path": "/api/safety-effort/submissions/:id",
    "documentedPath": "/api/safety-effort/submissions/:id",
    "purpose": "soft delete submission",
    "caller": "Safety Admin Report History",
    "whenCalled": "ลบรายงาน",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "soft delete"
  },
  {
    "module": "Assessment",
    "method": "GET",
    "path": "/api/safety-effort/assessment-templates",
    "documentedPath": "/api/safety-effort/assessment-templates?locationType=&activityType=",
    "purpose": "ดึง template แบบประเมิน",
    "caller": "Linewalk",
    "whenCalled": "ก่อนเริ่มตอบ",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "cache ได้"
  },
  {
    "module": "Assessment",
    "method": "POST",
    "path": "/api/safety-effort/assessment-runs",
    "documentedPath": "/api/safety-effort/assessment-runs",
    "purpose": "สร้าง/ส่งแบบประเมิน",
    "caller": "Assessment Summary",
    "whenCalled": "เมื่อบันทึก",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "payload ไม่ฝัง base64"
  },
  {
    "module": "Assessment",
    "method": "GET",
    "path": "/api/safety-effort/assessment-runs/:id",
    "documentedPath": "/api/safety-effort/assessment-runs/:id",
    "purpose": "อ่านผลแบบประเมิน",
    "caller": "History/Admin",
    "whenCalled": "เปิด detail",
    "auth": "User/Admin",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "รวม answers + media refs"
  },
  {
    "module": "Assessment",
    "method": "GET",
    "path": "/api/safety-effort/assessment-runs",
    "documentedPath": "/api/safety-effort/assessment-runs?from=&to=&locationType=&page=&pageSize=",
    "purpose": "รายงานแบบประเมิน",
    "caller": "Safety Admin",
    "whenCalled": "เปิด report",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": "export แยก endpoint"
  },
  {
    "module": "Assessment",
    "method": "GET",
    "path": "/api/safety-effort/assessment-runs/export",
    "documentedPath": "/api/safety-effort/assessment-runs/export?from=&to=&format=xlsx",
    "purpose": "export รายงานแบบประเมิน",
    "caller": "Safety Admin",
    "whenCalled": "กด export",
    "auth": "Admin",
    "pagination": "Stream/export job",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": "สำหรับไฟล์ใหญ่ควรใช้ async job"
  },
  {
    "module": "Safety Effort",
    "method": "POST",
    "path": "/api/safety-effort/findings",
    "documentedPath": "/api/safety-effort/findings",
    "purpose": "บันทึก safety finding",
    "caller": "Linewalk/Observation",
    "whenCalled": "เมื่อพบจุดเสี่ยง",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "แยก finding จาก answer ถ้าต้อง track action"
  },
  {
    "module": "Safety Effort",
    "method": "POST",
    "path": "/api/safety-effort/corrective-actions",
    "documentedPath": "/api/safety-effort/corrective-actions",
    "purpose": "สร้างงานแก้ไข",
    "caller": "Admin/Finding",
    "whenCalled": "เมื่อ assign",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "ผูก safety_findings"
  },
  {
    "module": "Safety Effort",
    "method": "GET",
    "path": "/api/safety-effort/corrective-actions",
    "documentedPath": "/api/safety-effort/corrective-actions?status=&assigneeId=&page=&pageSize=",
    "purpose": "รายการงานแก้ไข",
    "caller": "Admin/Dashboard",
    "whenCalled": "ติดตามงาน",
    "auth": "User/Admin",
    "pagination": "Required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "dashboard action"
  },
  {
    "module": "Were OK",
    "method": "POST",
    "path": "/api/were-ok/health-checks",
    "documentedPath": "/api/were-ok/health-checks",
    "purpose": "บันทึก Fit to Drive/health check",
    "caller": "Were OK",
    "whenCalled": "หลัง submit",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "รูป BP/Alc ใช้ uploads"
  },
  {
    "module": "Were OK",
    "method": "POST",
    "path": "/api/were-ok/pretrip-checks",
    "documentedPath": "/api/were-ok/pretrip-checks",
    "purpose": "บันทึก Pre-trip Check",
    "caller": "Were OK",
    "whenCalled": "หลัง submit",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "payload JSON + activityId"
  },
  {
    "module": "Were OK",
    "method": "POST",
    "path": "/api/were-ok/kyt-records",
    "documentedPath": "/api/were-ok/kyt-records",
    "purpose": "บันทึก KYT",
    "caller": "Were OK",
    "whenCalled": "หลัง submit",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "รูป KYT ใช้ uploads"
  },
  {
    "module": "Were OK",
    "method": "POST",
    "path": "/api/were-ok/sos-events",
    "documentedPath": "/api/were-ok/sos-events",
    "purpose": "บันทึก SOS",
    "caller": "Were OK",
    "whenCalled": "หลัง submit",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "แจ้งเตือน admin"
  },
  {
    "module": "Were OK",
    "method": "GET",
    "path": "/api/were-ok/jobs/current",
    "documentedPath": "/api/were-ok/jobs/current",
    "purpose": "อ่านงานวิ่งปัจจุบันของผู้ใช้",
    "caller": "Were OK / Route Briefing",
    "whenCalled": "หลังเข้าคิวหรือเปิดหน้า briefing",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "คืน null ถ้ายังไม่มีงานจริง ไม่ใช้ mock"
  },
  {
    "module": "Were OK",
    "method": "POST",
    "path": "/api/were-ok/jobs",
    "documentedPath": "/api/were-ok/jobs",
    "purpose": "สร้างหรือ upsert งานวิ่งจากระบบ dispatch",
    "caller": "Dispatch/Admin Integration",
    "whenCalled": "เมื่อระบบจ่ายงานส่งงานใหม่",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "รองรับ routeWarnings และ sleepSummary"
  },
  {
    "module": "Were OK",
    "method": "GET",
    "path": "/api/were-ok/jobs/:id",
    "documentedPath": "/api/were-ok/jobs/:id",
    "purpose": "อ่านรายละเอียดงานวิ่งรายตัว",
    "caller": "Were OK / Route Briefing",
    "whenCalled": "เปิดรายละเอียดงาน",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "จำกัดตาม user_id หรืองานที่ยังไม่ assign user"
  },
  {
    "module": "Were OK",
    "method": "POST",
    "path": "/api/were-ok/jobs/:id/acknowledge",
    "documentedPath": "/api/were-ok/jobs/:id/acknowledge",
    "purpose": "ยืนยันรับทราบงานวิ่ง",
    "caller": "Route Briefing",
    "whenCalled": "เมื่อ driver กดยืนยันงานวิ่ง",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "อัปเดต acknowledged_at"
  },
  {
    "module": "Safety Culture",
    "method": "GET",
    "path": "/api/safety-culture/posts",
    "documentedPath": "/api/safety-culture/posts?category=&cursor=&limit=",
    "purpose": "feed posts",
    "caller": "Safety Culture feed",
    "whenCalled": "เปิด feed/scroll",
    "auth": "User",
    "pagination": "Cursor required",
    "responseSizeRisk": "High if unpaged",
    "status": "Existing",
    "notes": "แทน localStorage posts"
  },
  {
    "module": "Safety Culture",
    "method": "POST",
    "path": "/api/safety-culture/posts",
    "documentedPath": "/api/safety-culture/posts",
    "purpose": "สร้าง post",
    "caller": "Post page",
    "whenCalled": "กดโพสต์",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "ส่ง attachmentIds ไม่ส่ง base64"
  },
  {
    "module": "Safety Culture",
    "method": "GET",
    "path": "/api/safety-culture/posts/:id",
    "documentedPath": "/api/safety-culture/posts/:id",
    "purpose": "รายละเอียด post",
    "caller": "Post detail/notification",
    "whenCalled": "เปิดจาก notification",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "รวม comments page แรก"
  },
  {
    "module": "Safety Culture",
    "method": "PATCH",
    "path": "/api/safety-culture/posts/:id",
    "documentedPath": "/api/safety-culture/posts/:id",
    "purpose": "แก้ post",
    "caller": "My post/admin",
    "whenCalled": "save edit",
    "auth": "Owner/Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "optional"
  },
  {
    "module": "Safety Culture",
    "method": "DELETE",
    "path": "/api/safety-culture/posts/:id",
    "documentedPath": "/api/safety-culture/posts/:id",
    "purpose": "soft delete post",
    "caller": "My post/admin",
    "whenCalled": "delete",
    "auth": "Owner/Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "soft delete"
  },
  {
    "module": "Safety Culture",
    "method": "POST",
    "path": "/api/safety-culture/posts/:id/comments",
    "documentedPath": "/api/safety-culture/posts/:id/comments",
    "purpose": "เพิ่ม comment",
    "caller": "Feed/Post detail",
    "whenCalled": "ส่ง comment",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "ให้คะแนนตาม rule"
  },
  {
    "module": "Safety Culture",
    "method": "GET",
    "path": "/api/safety-culture/posts/:id/comments",
    "documentedPath": "/api/safety-culture/posts/:id/comments?cursor=&limit=",
    "purpose": "โหลด comments เพิ่ม",
    "caller": "Post detail",
    "whenCalled": "scroll comments",
    "auth": "User",
    "pagination": "Cursor required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "แยกจาก feed"
  },
  {
    "module": "Safety Culture",
    "method": "PATCH",
    "path": "/api/safety-culture/comments/:id",
    "documentedPath": "/api/safety-culture/comments/:id",
    "purpose": "แก้ comment ของตัวเอง",
    "caller": "Feed/Post detail",
    "whenCalled": "save edit comment",
    "auth": "Owner",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "owner only"
  },
  {
    "module": "Safety Culture",
    "method": "DELETE",
    "path": "/api/safety-culture/comments/:id",
    "documentedPath": "/api/safety-culture/comments/:id",
    "purpose": "ลบ comment ของตัวเอง",
    "caller": "Feed/Post detail",
    "whenCalled": "delete comment",
    "auth": "Owner",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "soft delete owner only"
  },
  {
    "module": "Safety Culture",
    "method": "POST",
    "path": "/api/safety-culture/posts/:id/reactions",
    "documentedPath": "/api/safety-culture/posts/:id/reactions",
    "purpose": "like/reaction",
    "caller": "Feed",
    "whenCalled": "กด reaction",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "upsert reaction"
  },
  {
    "module": "Safety Culture",
    "method": "DELETE",
    "path": "/api/safety-culture/posts/:id/reactions",
    "documentedPath": "/api/safety-culture/posts/:id/reactions",
    "purpose": "ยกเลิก reaction",
    "caller": "Feed",
    "whenCalled": "unlike",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "delete reaction"
  },
  {
    "module": "Safety Culture",
    "method": "GET",
    "path": "/api/safety-culture/events",
    "documentedPath": "/api/safety-culture/events?status=&page=&pageSize=",
    "purpose": "รายการกิจกรรม culture",
    "caller": "Feed/Admin Event",
    "whenCalled": "เปิดกิจกรรม",
    "auth": "User",
    "pagination": "Required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "live/scheduled/closed"
  },
  {
    "module": "Safety Culture",
    "method": "POST",
    "path": "/api/safety-culture/events",
    "documentedPath": "/api/safety-culture/events",
    "purpose": "สร้างกิจกรรม",
    "caller": "Admin Event",
    "whenCalled": "admin save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "แทน localStorage"
  },
  {
    "module": "Safety Culture",
    "method": "PATCH",
    "path": "/api/safety-culture/events/:id",
    "documentedPath": "/api/safety-culture/events/:id",
    "purpose": "แก้กิจกรรม",
    "caller": "Admin Event",
    "whenCalled": "admin save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "audit"
  },
  {
    "module": "Safety Culture",
    "method": "GET",
    "path": "/api/safety-culture/leaderboard",
    "documentedPath": "/api/safety-culture/leaderboard?scope=&period=",
    "purpose": "leaderboard",
    "caller": "Leaderboard",
    "whenCalled": "เปิดหน้า",
    "auth": "User",
    "pagination": "Limit/cached",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "cache รายช่วงเวลา"
  },
  {
    "module": "Safety Culture",
    "method": "GET",
    "path": "/api/safety-culture/rewards",
    "documentedPath": "/api/safety-culture/rewards",
    "purpose": "catalog ของรางวัล",
    "caller": "Rewards",
    "whenCalled": "เปิดหน้า",
    "auth": "User",
    "pagination": "No or page",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "cache ได้"
  },
  {
    "module": "Safety Culture",
    "method": "POST",
    "path": "/api/safety-culture/rewards/:id/redeem",
    "documentedPath": "/api/safety-culture/rewards/:id/redeem",
    "purpose": "แลกรางวัล",
    "caller": "Rewards",
    "whenCalled": "กด redeem",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "transactional"
  },
  {
    "module": "Safety Awareness",
    "method": "GET",
    "path": "/api/safety-awareness/questions",
    "documentedPath": "/api/safety-awareness/questions?date=",
    "purpose": "คำถาม awareness ของวัน",
    "caller": "Popup/Admin",
    "whenCalled": "เปิด popup",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "cache by date"
  },
  {
    "module": "Safety Awareness",
    "method": "POST",
    "path": "/api/safety-awareness/attempts",
    "documentedPath": "/api/safety-awareness/attempts",
    "purpose": "ส่งคำตอบ awareness",
    "caller": "Popup",
    "whenCalled": "submit",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "บันทึก attempt"
  },
  {
    "module": "Notifications",
    "method": "GET",
    "path": "/api/notifications",
    "documentedPath": "/api/notifications?cursor=&limit=",
    "purpose": "inbox notifications",
    "caller": "Notifications",
    "whenCalled": "เปิด inbox",
    "auth": "User",
    "pagination": "Cursor required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "แทน in-memory/localStorage"
  },
  {
    "module": "Notifications",
    "method": "PATCH",
    "path": "/api/notifications/:id/read",
    "documentedPath": "/api/notifications/:id/read",
    "purpose": "mark read",
    "caller": "Notifications",
    "whenCalled": "อ่านรายการ",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Notifications",
    "method": "POST",
    "path": "/api/notifications/broadcast",
    "documentedPath": "/api/notifications/broadcast",
    "purpose": "ส่ง notification จาก admin/event",
    "caller": "Admin",
    "whenCalled": "กดส่ง",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "อาจ queue"
  },
  {
    "module": "Uploads",
    "method": "POST",
    "path": "/api/uploads",
    "documentedPath": "/api/uploads",
    "purpose": "upload รูป/ไฟล์กลางระบบ",
    "caller": "Safety Effort, Culture, Profile",
    "whenCalled": "เลือก/ถ่ายรูป",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Upload size limit",
    "status": "Existing",
    "notes": "multipart/form-data"
  },
  {
    "module": "Uploads",
    "method": "GET",
    "path": "/api/uploads/:id",
    "documentedPath": "/api/uploads/:id",
    "purpose": "อ่าน metadata ไฟล์",
    "caller": "Any detail page",
    "whenCalled": "เมื่อโหลด owner",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "ตรวจสิทธิ์"
  },
  {
    "module": "Uploads",
    "method": "GET",
    "path": "/api/uploads/:id/download",
    "documentedPath": "/api/uploads/:id/download",
    "purpose": "download/private signed URL",
    "caller": "Image viewer/report",
    "whenCalled": "เมื่อเปิดรูป",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "File",
    "status": "Existing",
    "notes": "ใช้ signed URL/private URL"
  },
  {
    "module": "Uploads",
    "method": "DELETE",
    "path": "/api/uploads/:id",
    "documentedPath": "/api/uploads/:id",
    "purpose": "ลบ/ยกเลิก attachment",
    "caller": "Draft/Admin",
    "whenCalled": "ลบรูป",
    "auth": "Owner/Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "soft delete + object lifecycle"
  },
  {
    "module": "Uploads",
    "method": "POST",
    "path": "/api/uploads/cleanup-drafts",
    "documentedPath": "/api/uploads/cleanup-drafts",
    "purpose": "cleanup draft media",
    "caller": "Scheduled job",
    "whenCalled": "ตามรอบเวลา",
    "auth": "System/Admin",
    "pagination": "Batch cap",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "ลบรูปที่ไม่ถูกผูกกับ owner"
  },
  {
    "module": "Organizations",
    "method": "GET",
    "path": "/api/organizations/tree",
    "documentedPath": "/api/organizations/tree",
    "purpose": "อ่านโครงสร้างองค์กรแบบ tree",
    "caller": "Admin, Profile, Location admin",
    "whenCalled": "เปิดตัวกรององค์กร",
    "auth": "Admin/User scoped",
    "pagination": "No or shallow depth",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "ใช้กับ company/division/fact/section"
  },
  {
    "module": "Organizations",
    "method": "GET",
    "path": "/api/organizations",
    "documentedPath": "/api/organizations?parentId=&type=&page=&pageSize=",
    "purpose": "รายการองค์กรแบบแบ่งหน้า",
    "caller": "Admin",
    "whenCalled": "ค้น/จัดการองค์กร",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "ไม่โหลด tree ใหญ่ทุกครั้ง"
  },
  {
    "module": "Organizations",
    "method": "GET",
    "path": "/api/organizations/:id",
    "documentedPath": "/api/organizations/:id",
    "purpose": "รายละเอียดองค์กร",
    "caller": "Admin/Profile",
    "whenCalled": "เปิด detail",
    "auth": "Admin/User scoped",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Organizations",
    "method": "POST",
    "path": "/api/organizations",
    "documentedPath": "/api/organizations",
    "purpose": "สร้างองค์กร",
    "caller": "Admin",
    "whenCalled": "admin submit",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "audit required"
  },
  {
    "module": "Organizations",
    "method": "PATCH",
    "path": "/api/organizations/:id",
    "documentedPath": "/api/organizations/:id",
    "purpose": "แก้ข้อมูลองค์กร",
    "caller": "Admin",
    "whenCalled": "admin save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "audit required"
  },
  {
    "module": "Organizations",
    "method": "DELETE",
    "path": "/api/organizations/:id",
    "documentedPath": "/api/organizations/:id",
    "purpose": "soft delete องค์กร",
    "caller": "Admin",
    "whenCalled": "admin delete",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "ต้องตรวจ child ก่อนลบ"
  },
  {
    "module": "Users/IAM",
    "method": "GET",
    "path": "/api/users/me",
    "documentedPath": "/api/users/me",
    "purpose": "โปรไฟล์ผู้ใช้ปัจจุบัน",
    "caller": "Profile/Header",
    "whenCalled": "หลัง login",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "merge SSO + app profile"
  },
  {
    "module": "Users/IAM",
    "method": "PATCH",
    "path": "/api/users/me",
    "documentedPath": "/api/users/me",
    "purpose": "แก้ profile ผู้ใช้",
    "caller": "Profile",
    "whenCalled": "save profile",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "profile image ใช้ mediaId"
  },
  {
    "module": "Users/IAM",
    "method": "GET",
    "path": "/api/users",
    "documentedPath": "/api/users?search=&organizationId=&role=&page=&pageSize=",
    "purpose": "ค้นผู้ใช้",
    "caller": "Admin, Assign action",
    "whenCalled": "search/assign",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "ต้อง limit search"
  },
  {
    "module": "Users/IAM",
    "method": "GET",
    "path": "/api/users/:id",
    "documentedPath": "/api/users/:id",
    "purpose": "รายละเอียดผู้ใช้",
    "caller": "Admin",
    "whenCalled": "open detail",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Users/IAM",
    "method": "PATCH",
    "path": "/api/users/:id/status",
    "documentedPath": "/api/users/:id/status",
    "purpose": "เปลี่ยนสถานะ user",
    "caller": "Admin",
    "whenCalled": "active/inactive",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "audit required"
  },
  {
    "module": "Users/IAM",
    "method": "GET",
    "path": "/api/roles",
    "documentedPath": "/api/roles",
    "purpose": "รายการ role",
    "caller": "Admin",
    "whenCalled": "เปิด role admin",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Users/IAM",
    "method": "POST",
    "path": "/api/roles",
    "documentedPath": "/api/roles",
    "purpose": "สร้าง role",
    "caller": "Admin",
    "whenCalled": "save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Users/IAM",
    "method": "PATCH",
    "path": "/api/roles/:id",
    "documentedPath": "/api/roles/:id",
    "purpose": "แก้ role",
    "caller": "Admin",
    "whenCalled": "save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Users/IAM",
    "method": "GET",
    "path": "/api/permissions",
    "documentedPath": "/api/permissions",
    "purpose": "รายการ permission",
    "caller": "Admin",
    "whenCalled": "role setup",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Users/IAM",
    "method": "PUT",
    "path": "/api/users/:id/roles",
    "documentedPath": "/api/users/:id/roles",
    "purpose": "กำหนด roles ให้ user",
    "caller": "Admin",
    "whenCalled": "assign role",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "transactional"
  },
  {
    "module": "Users/IAM",
    "method": "PUT",
    "path": "/api/roles/:id/permissions",
    "documentedPath": "/api/roles/:id/permissions",
    "purpose": "กำหนด permissions ให้ role",
    "caller": "Admin",
    "whenCalled": "assign permission",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "transactional"
  },
  {
    "module": "Location Import",
    "method": "POST",
    "path": "/api/location-imports",
    "documentedPath": "/api/location-imports",
    "purpose": "upload/import master location file",
    "caller": "Admin",
    "whenCalled": "admin import DataOcean/Excel",
    "auth": "Admin",
    "pagination": "Upload/job",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": "สร้าง batch"
  },
  {
    "module": "Location Import",
    "method": "GET",
    "path": "/api/location-imports",
    "documentedPath": "/api/location-imports?status=&page=&pageSize=",
    "purpose": "รายการ import batch",
    "caller": "Admin",
    "whenCalled": "เปิด import history",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Location Import",
    "method": "GET",
    "path": "/api/location-imports/:id",
    "documentedPath": "/api/location-imports/:id",
    "purpose": "รายละเอียด import batch",
    "caller": "Admin",
    "whenCalled": "เปิด detail",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "รวม summary success/fail"
  },
  {
    "module": "Location Import",
    "method": "GET",
    "path": "/api/location-imports/:id/rows",
    "documentedPath": "/api/location-imports/:id/rows?page=&pageSize=&status=",
    "purpose": "แถว import",
    "caller": "Admin",
    "whenCalled": "ดู error rows",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": "จำเป็นต้องแบ่งหน้า"
  },
  {
    "module": "Location Import",
    "method": "POST",
    "path": "/api/location-imports/:id/retry",
    "documentedPath": "/api/location-imports/:id/retry",
    "purpose": "retry failed rows",
    "caller": "Admin",
    "whenCalled": "กด retry",
    "auth": "Admin",
    "pagination": "Batch cap",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Location Import",
    "method": "POST",
    "path": "/api/location-imports/:id/apply",
    "documentedPath": "/api/location-imports/:id/apply",
    "purpose": "apply staged import",
    "caller": "Admin",
    "whenCalled": "confirm import",
    "auth": "Admin",
    "pagination": "Async job",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": "upsert locations"
  },
  {
    "module": "Check-in",
    "method": "GET",
    "path": "/api/checkins/nearby",
    "documentedPath": "/api/checkins/nearby?lat=&lng=&radiusM=&type=",
    "purpose": "สถานที่ใกล้ฉัน",
    "caller": "Check-in",
    "whenCalled": "เมื่อเปิดหน้า/กด locate",
    "auth": "User",
    "pagination": "Limit required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "spatial distance query"
  },
  {
    "module": "Check-in",
    "method": "POST",
    "path": "/api/checkins/:id/attachments",
    "documentedPath": "/api/checkins/:id/attachments",
    "purpose": "ผูกรูป/หลักฐานกับ check-in",
    "caller": "Check-in",
    "whenCalled": "หลัง upload",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "ใช้ attachmentIds"
  },
  {
    "module": "Check-in",
    "method": "DELETE",
    "path": "/api/checkins/:id/attachments/:attachmentId",
    "documentedPath": "/api/checkins/:id/attachments/:attachmentId",
    "purpose": "ลบหลักฐาน check-in",
    "caller": "Check-in/Admin",
    "whenCalled": "remove photo",
    "auth": "Owner/Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Check-in",
    "method": "GET",
    "path": "/api/checkins/stats",
    "documentedPath": "/api/checkins/stats?from=&to=&locationType=",
    "purpose": "สถิติ check-in",
    "caller": "Dashboard/Admin",
    "whenCalled": "เปิด dashboard",
    "auth": "Admin",
    "pagination": "Aggregate",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "ใช้ aggregate/cache"
  },
  {
    "module": "Assessment Admin",
    "method": "GET",
    "path": "/api/safety-effort/assessment-templates/:id",
    "documentedPath": "/api/safety-effort/assessment-templates/:id",
    "purpose": "รายละเอียด template",
    "caller": "Safety Admin",
    "whenCalled": "open template",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Assessment Admin",
    "method": "POST",
    "path": "/api/safety-effort/assessment-templates",
    "documentedPath": "/api/safety-effort/assessment-templates",
    "purpose": "สร้าง template",
    "caller": "Safety Admin",
    "whenCalled": "save template",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "versioned"
  },
  {
    "module": "Assessment Admin",
    "method": "PATCH",
    "path": "/api/safety-effort/assessment-templates/:id",
    "documentedPath": "/api/safety-effort/assessment-templates/:id",
    "purpose": "แก้ template metadata",
    "caller": "Safety Admin",
    "whenCalled": "save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Assessment Admin",
    "method": "POST",
    "path": "/api/safety-effort/assessment-templates/:id/publish",
    "documentedPath": "/api/safety-effort/assessment-templates/:id/publish",
    "purpose": "publish template version",
    "caller": "Safety Admin",
    "whenCalled": "publish",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "lock questions"
  },
  {
    "module": "Assessment Admin",
    "method": "POST",
    "path": "/api/safety-effort/assessment-templates/:id/archive",
    "documentedPath": "/api/safety-effort/assessment-templates/:id/archive",
    "purpose": "archive template",
    "caller": "Safety Admin",
    "whenCalled": "archive",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Assessment Admin",
    "method": "GET",
    "path": "/api/safety-effort/assessment-templates/:id/questions",
    "documentedPath": "/api/safety-effort/assessment-templates/:id/questions",
    "purpose": "รายการคำถามใน template",
    "caller": "Safety Admin/Linewalk",
    "whenCalled": "load questions",
    "auth": "User/Admin",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Assessment Admin",
    "method": "POST",
    "path": "/api/safety-effort/assessment-templates/:id/questions",
    "documentedPath": "/api/safety-effort/assessment-templates/:id/questions",
    "purpose": "เพิ่มคำถาม",
    "caller": "Safety Admin",
    "whenCalled": "save question",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Assessment Admin",
    "method": "PATCH",
    "path": "/api/safety-effort/questions/:id",
    "documentedPath": "/api/safety-effort/questions/:id",
    "purpose": "แก้คำถาม",
    "caller": "Safety Admin",
    "whenCalled": "save question",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Assessment Admin",
    "method": "DELETE",
    "path": "/api/safety-effort/questions/:id",
    "documentedPath": "/api/safety-effort/questions/:id",
    "purpose": "ลบ/disable คำถาม",
    "caller": "Safety Admin",
    "whenCalled": "delete",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "soft disable if published"
  },
  {
    "module": "Assessment",
    "method": "POST",
    "path": "/api/safety-effort/assessment-runs/:id/submit",
    "documentedPath": "/api/safety-effort/assessment-runs/:id/submit",
    "purpose": "submit draft assessment",
    "caller": "Assessment Summary",
    "whenCalled": "confirm save",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "server validates complete answers"
  },
  {
    "module": "Assessment",
    "method": "PATCH",
    "path": "/api/safety-effort/assessment-runs/:id/draft",
    "documentedPath": "/api/safety-effort/assessment-runs/:id/draft",
    "purpose": "save draft",
    "caller": "Linewalk",
    "whenCalled": "autosave/manual save",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "attachmentIds only"
  },
  {
    "module": "Assessment",
    "method": "POST",
    "path": "/api/safety-effort/assessment-runs/:id/attachments",
    "documentedPath": "/api/safety-effort/assessment-runs/:id/attachments",
    "purpose": "ผูกรูปกับ run/answer",
    "caller": "Linewalk",
    "whenCalled": "after upload",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Reports",
    "method": "GET",
    "path": "/api/safety-effort/reports/summary",
    "documentedPath": "/api/safety-effort/reports/summary?from=&to=&locationType=",
    "purpose": "summary cards สำหรับ admin",
    "caller": "Safety Admin",
    "whenCalled": "เปิด dashboard",
    "auth": "Admin",
    "pagination": "Aggregate",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "cache by filter"
  },
  {
    "module": "Reports",
    "method": "GET",
    "path": "/api/safety-effort/reports/by-location",
    "documentedPath": "/api/safety-effort/reports/by-location?from=&to=&type=&page=&pageSize=",
    "purpose": "รายงานแยก location",
    "caller": "Safety Admin",
    "whenCalled": "open report",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Reports",
    "method": "GET",
    "path": "/api/safety-effort/reports/by-user",
    "documentedPath": "/api/safety-effort/reports/by-user?from=&to=&page=&pageSize=",
    "purpose": "รายงานแยกผู้ประเมิน",
    "caller": "Safety Admin",
    "whenCalled": "open report",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Reports",
    "method": "GET",
    "path": "/api/safety-effort/reports/findings",
    "documentedPath": "/api/safety-effort/reports/findings?from=&to=&status=&page=&pageSize=",
    "purpose": "รายงาน finding",
    "caller": "Safety Admin",
    "whenCalled": "open report",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Reports",
    "method": "POST",
    "path": "/api/exports",
    "documentedPath": "/api/exports",
    "purpose": "สร้าง export job",
    "caller": "Admin",
    "whenCalled": "กด export ใหญ่",
    "auth": "Admin",
    "pagination": "Async",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": "ใช้ได้หลาย module"
  },
  {
    "module": "Reports",
    "method": "GET",
    "path": "/api/exports/:id",
    "documentedPath": "/api/exports/:id",
    "purpose": "สถานะ export job",
    "caller": "Admin",
    "whenCalled": "poll status",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Reports",
    "method": "GET",
    "path": "/api/exports/:id/download",
    "documentedPath": "/api/exports/:id/download",
    "purpose": "download export file",
    "caller": "Admin",
    "whenCalled": "download",
    "auth": "Admin",
    "pagination": "File",
    "responseSizeRisk": "File",
    "status": "Existing",
    "notes": "signed URL or stream"
  },
  {
    "module": "Corrective Action",
    "method": "GET",
    "path": "/api/safety-effort/findings",
    "documentedPath": "/api/safety-effort/findings?status=&severity=&page=&pageSize=",
    "purpose": "รายการ findings",
    "caller": "Admin/Dashboard",
    "whenCalled": "ติดตามจุดเสี่ยง",
    "auth": "User/Admin",
    "pagination": "Required",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Corrective Action",
    "method": "GET",
    "path": "/api/safety-effort/findings/:id",
    "documentedPath": "/api/safety-effort/findings/:id",
    "purpose": "รายละเอียด finding",
    "caller": "Admin/Assignee",
    "whenCalled": "open detail",
    "auth": "User/Admin",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "รวม action/media"
  },
  {
    "module": "Corrective Action",
    "method": "PATCH",
    "path": "/api/safety-effort/findings/:id",
    "documentedPath": "/api/safety-effort/findings/:id",
    "purpose": "แก้ finding",
    "caller": "Admin/Reporter",
    "whenCalled": "save",
    "auth": "Owner/Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Corrective Action",
    "method": "PATCH",
    "path": "/api/safety-effort/corrective-actions/:id",
    "documentedPath": "/api/safety-effort/corrective-actions/:id",
    "purpose": "อัปเดต action",
    "caller": "Assignee/Admin",
    "whenCalled": "update status",
    "auth": "Assignee/Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Corrective Action",
    "method": "POST",
    "path": "/api/safety-effort/corrective-actions/:id/complete",
    "documentedPath": "/api/safety-effort/corrective-actions/:id/complete",
    "purpose": "ปิดงานแก้ไข",
    "caller": "Assignee/Admin",
    "whenCalled": "complete",
    "auth": "Assignee/Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "require evidence optional"
  },
  {
    "module": "Corrective Action",
    "method": "POST",
    "path": "/api/safety-effort/corrective-actions/:id/comments",
    "documentedPath": "/api/safety-effort/corrective-actions/:id/comments",
    "purpose": "comment ใน action",
    "caller": "Assignee/Admin",
    "whenCalled": "add comment",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Safety Culture Admin",
    "method": "GET",
    "path": "/api/safety-culture/posts/admin",
    "documentedPath": "/api/safety-culture/posts/admin?status=&page=&pageSize=",
    "purpose": "admin moderation list",
    "caller": "Admin Culture",
    "whenCalled": "เปิดจัดการโพสต์",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Safety Culture Admin",
    "method": "POST",
    "path": "/api/safety-culture/posts/:id/approve",
    "documentedPath": "/api/safety-culture/posts/:id/approve",
    "purpose": "approve post",
    "caller": "Admin Culture",
    "whenCalled": "approve",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "optional if moderation enabled"
  },
  {
    "module": "Safety Culture Admin",
    "method": "POST",
    "path": "/api/safety-culture/posts/:id/reject",
    "documentedPath": "/api/safety-culture/posts/:id/reject",
    "purpose": "reject post",
    "caller": "Admin Culture",
    "whenCalled": "reject",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "with reason"
  },
  {
    "module": "Safety Culture",
    "method": "GET",
    "path": "/api/safety-culture/events/:id",
    "documentedPath": "/api/safety-culture/events/:id",
    "purpose": "รายละเอียดกิจกรรม",
    "caller": "Feed/Admin",
    "whenCalled": "open event",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Safety Culture",
    "method": "POST",
    "path": "/api/safety-culture/events/:id/notify",
    "documentedPath": "/api/safety-culture/events/:id/notify",
    "purpose": "ส่ง notification กิจกรรม",
    "caller": "Admin Event",
    "whenCalled": "กดส่งแจ้งเตือน",
    "auth": "Admin",
    "pagination": "Batch/queue",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Safety Culture",
    "method": "GET",
    "path": "/api/safety-culture/points/me",
    "documentedPath": "/api/safety-culture/points/me",
    "purpose": "คะแนนของฉัน",
    "caller": "Profile/Rewards",
    "whenCalled": "เปิดหน้า",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Safety Culture",
    "method": "GET",
    "path": "/api/safety-culture/points/me/transactions",
    "documentedPath": "/api/safety-culture/points/me/transactions?cursor=&limit=",
    "purpose": "ledger คะแนนของฉัน",
    "caller": "Profile history",
    "whenCalled": "scroll",
    "auth": "User",
    "pagination": "Cursor",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Safety Culture Admin",
    "method": "GET",
    "path": "/api/safety-culture/points/rules",
    "documentedPath": "/api/safety-culture/points/rules",
    "purpose": "กติกาคะแนน",
    "caller": "Admin",
    "whenCalled": "open settings",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Safety Culture Admin",
    "method": "PATCH",
    "path": "/api/safety-culture/points/rules/:id",
    "documentedPath": "/api/safety-culture/points/rules/:id",
    "purpose": "แก้กติกาคะแนน",
    "caller": "Admin",
    "whenCalled": "save rule",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "audit required"
  },
  {
    "module": "Safety Culture Admin",
    "method": "POST",
    "path": "/api/safety-culture/points/adjustments",
    "documentedPath": "/api/safety-culture/points/adjustments",
    "purpose": "ปรับคะแนน manual",
    "caller": "Admin",
    "whenCalled": "manual adjustment",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "audit + reason required"
  },
  {
    "module": "Rewards Admin",
    "method": "POST",
    "path": "/api/safety-culture/rewards",
    "documentedPath": "/api/safety-culture/rewards",
    "purpose": "สร้างของรางวัล",
    "caller": "Admin Reward",
    "whenCalled": "save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "reward image mediaId"
  },
  {
    "module": "Rewards Admin",
    "method": "PATCH",
    "path": "/api/safety-culture/rewards/:id",
    "documentedPath": "/api/safety-culture/rewards/:id",
    "purpose": "แก้ของรางวัล",
    "caller": "Admin Reward",
    "whenCalled": "save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Rewards Admin",
    "method": "DELETE",
    "path": "/api/safety-culture/rewards/:id",
    "documentedPath": "/api/safety-culture/rewards/:id",
    "purpose": "ซ่อน/ลบของรางวัล",
    "caller": "Admin Reward",
    "whenCalled": "delete",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "soft delete"
  },
  {
    "module": "Rewards Admin",
    "method": "GET",
    "path": "/api/safety-culture/reward-redemptions",
    "documentedPath": "/api/safety-culture/reward-redemptions?status=&page=&pageSize=",
    "purpose": "รายการแลกรางวัล",
    "caller": "Admin Reward",
    "whenCalled": "เปิด admin",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Rewards Admin",
    "method": "PATCH",
    "path": "/api/safety-culture/reward-redemptions/:id/status",
    "documentedPath": "/api/safety-culture/reward-redemptions/:id/status",
    "purpose": "อัปเดตสถานะแลกรางวัล",
    "caller": "Admin Reward",
    "whenCalled": "approve/fulfill/cancel",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "transaction-safe"
  },
  {
    "module": "Rewards Admin",
    "method": "POST",
    "path": "/api/safety-culture/rewards/:id/inventory-transactions",
    "documentedPath": "/api/safety-culture/rewards/:id/inventory-transactions",
    "purpose": "ปรับ stock ของรางวัล",
    "caller": "Admin Reward",
    "whenCalled": "stock in/out",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "ledger"
  },
  {
    "module": "Awareness Admin",
    "method": "GET",
    "path": "/api/safety-awareness/questions/admin",
    "documentedPath": "/api/safety-awareness/questions/admin?page=&pageSize=&category=",
    "purpose": "คลังคำถาม awareness",
    "caller": "Admin Awareness",
    "whenCalled": "open admin",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Awareness Admin",
    "method": "POST",
    "path": "/api/safety-awareness/questions",
    "documentedPath": "/api/safety-awareness/questions",
    "purpose": "สร้างคำถาม awareness",
    "caller": "Admin Awareness",
    "whenCalled": "save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Awareness Admin",
    "method": "PATCH",
    "path": "/api/safety-awareness/questions/:id",
    "documentedPath": "/api/safety-awareness/questions/:id",
    "purpose": "แก้คำถาม awareness",
    "caller": "Admin Awareness",
    "whenCalled": "save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Awareness Admin",
    "method": "DELETE",
    "path": "/api/safety-awareness/questions/:id",
    "documentedPath": "/api/safety-awareness/questions/:id",
    "purpose": "disable คำถาม awareness",
    "caller": "Admin Awareness",
    "whenCalled": "delete",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "soft disable"
  },
  {
    "module": "Awareness",
    "method": "GET",
    "path": "/api/safety-awareness/attempts/me",
    "documentedPath": "/api/safety-awareness/attempts/me?from=&to=&page=&pageSize=",
    "purpose": "ประวัติ awareness ของฉัน",
    "caller": "Profile",
    "whenCalled": "open history",
    "auth": "User",
    "pagination": "Required",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Awareness Admin",
    "method": "GET",
    "path": "/api/safety-awareness/attempts",
    "documentedPath": "/api/safety-awareness/attempts?from=&to=&userId=&page=&pageSize=",
    "purpose": "รายงาน awareness",
    "caller": "Admin Awareness",
    "whenCalled": "open report",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Holidays",
    "method": "GET",
    "path": "/api/holidays",
    "documentedPath": "/api/holidays?year=",
    "purpose": "รายการวันหยุด",
    "caller": "Admin Awareness/Effort",
    "whenCalled": "เปิด settings/date rules",
    "auth": "User/Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "cache yearly"
  },
  {
    "module": "Holidays",
    "method": "POST",
    "path": "/api/holidays",
    "documentedPath": "/api/holidays",
    "purpose": "เพิ่มวันหยุด",
    "caller": "Admin",
    "whenCalled": "save",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Holidays",
    "method": "DELETE",
    "path": "/api/holidays/:id",
    "documentedPath": "/api/holidays/:id",
    "purpose": "ลบวันหยุด",
    "caller": "Admin",
    "whenCalled": "delete",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Notifications",
    "method": "POST",
    "path": "/api/notifications/:id/archive",
    "documentedPath": "/api/notifications/:id/archive",
    "purpose": "archive notification",
    "caller": "Notifications",
    "whenCalled": "archive",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Notifications",
    "method": "PATCH",
    "path": "/api/notifications/read-all",
    "documentedPath": "/api/notifications/read-all",
    "purpose": "mark all read",
    "caller": "Notifications",
    "whenCalled": "กดอ่านทั้งหมด",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Notifications",
    "method": "GET",
    "path": "/api/notifications/preferences",
    "documentedPath": "/api/notifications/preferences",
    "purpose": "notification preferences",
    "caller": "Profile",
    "whenCalled": "open settings",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Notifications",
    "method": "PATCH",
    "path": "/api/notifications/preferences",
    "documentedPath": "/api/notifications/preferences",
    "purpose": "แก้ notification preferences",
    "caller": "Profile",
    "whenCalled": "save settings",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Media",
    "method": "POST",
    "path": "/api/uploads/:id/link",
    "documentedPath": "/api/uploads/:id/link",
    "purpose": "ผูก media กับ owner",
    "caller": "Any module",
    "whenCalled": "หลังสร้าง owner หรือ attach เพิ่ม",
    "auth": "Owner/Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "ownerType/ownerId/linkType"
  },
  {
    "module": "Media",
    "method": "DELETE",
    "path": "/api/uploads/:id/link",
    "documentedPath": "/api/uploads/:id/link",
    "purpose": "ถอด media จาก owner",
    "caller": "Any module",
    "whenCalled": "remove attachment",
    "auth": "Owner/Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "Media",
    "method": "GET",
    "path": "/api/media",
    "documentedPath": "/api/media?ownerType=&ownerId=",
    "purpose": "อ่าน media ของ owner",
    "caller": "Detail/report",
    "whenCalled": "โหลด detail",
    "auth": "User",
    "pagination": "Limit",
    "responseSizeRisk": "Medium",
    "status": "Existing",
    "notes": "ตรวจสิทธิ์ตาม owner"
  },
  {
    "module": "Media",
    "method": "POST",
    "path": "/api/uploads/presign",
    "documentedPath": "/api/uploads/presign",
    "purpose": "ขอ signed upload URL",
    "caller": "Mobile/Web",
    "whenCalled": "ก่อน upload direct-to-storage",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "optional for scale"
  },
  {
    "module": "Media",
    "method": "POST",
    "path": "/api/uploads/:id/complete",
    "documentedPath": "/api/uploads/:id/complete",
    "purpose": "ยืนยัน upload direct-to-storage",
    "caller": "Mobile/Web",
    "whenCalled": "หลัง upload สำเร็จ",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "verify object exists"
  },
  {
    "module": "Safety Culture",
    "method": "GET",
    "path": "/api/safety-culture/teams",
    "documentedPath": "/api/safety-culture/teams",
    "purpose": "อ่านทีมสำหรับหน้า admin leaderboard",
    "caller": "Admin Leaderboard",
    "whenCalled": "เปิดหน้าจัดการทีม",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "อ่านจาก teams และ team_members"
  },
  {
    "module": "Safety Culture",
    "method": "PUT",
    "path": "/api/safety-culture/teams",
    "documentedPath": "/api/safety-culture/teams",
    "purpose": "บันทึกรายการทีมสำหรับ leaderboard",
    "caller": "Admin Leaderboard",
    "whenCalled": "เมื่อ admin บันทึกทีม",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "upsert/soft-delete teams"
  },
  {
    "module": "Settings",
    "method": "GET",
    "path": "/api/safety-settings",
    "documentedPath": "/api/safety-settings?key=",
    "purpose": "อ่านค่า safety settings จากฐานจริง",
    "caller": "Safety Admin/DatePicker",
    "whenCalled": "โหลดหน้าหรือเปิด setting",
    "auth": "User",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "ใช้ safety_settings ไม่ใช้ localStorage"
  },
  {
    "module": "Settings",
    "method": "PUT",
    "path": "/api/safety-settings",
    "documentedPath": "/api/safety-settings",
    "purpose": "บันทึกค่า safety settings ลงฐานจริง",
    "caller": "Safety Admin",
    "whenCalled": "เมื่อ admin save settings",
    "auth": "Admin",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": "upsert safety_settings"
  },
  {
    "module": "Audit",
    "method": "GET",
    "path": "/api/audit-logs",
    "documentedPath": "/api/audit-logs?actor=&entity=&from=&to=&page=&pageSize=",
    "purpose": "audit trail",
    "caller": "Admin/Security",
    "whenCalled": "ตรวจสอบการแก้ไข",
    "auth": "Admin",
    "pagination": "Required",
    "responseSizeRisk": "High",
    "status": "Existing",
    "notes": "ห้ามเปิด public"
  },
  {
    "module": "System",
    "method": "GET",
    "path": "/api/health",
    "documentedPath": "/api/health",
    "purpose": "health check",
    "caller": "Infra",
    "whenCalled": "monitoring",
    "auth": "Public/Internal",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  },
  {
    "module": "System",
    "method": "GET",
    "path": "/api/version",
    "documentedPath": "/api/version",
    "purpose": "app/api version",
    "caller": "Infra/Debug",
    "whenCalled": "debug",
    "auth": "Public/Internal",
    "pagination": "No",
    "responseSizeRisk": "Small",
    "status": "Existing",
    "notes": ""
  }
] as const satisfies readonly ApiCatalogRoute[];
